### ISSUE TITLE
Error on bean-extract

### ISSUE THREAD

**Issue by RockerFlower** [lidongchao/BeancountSample#1]
**`$ bean-extract my.config Csv/2018-01-2.csv > Data/2018-01-2.beancount`**

```
ERROR:root:Importer alipay.Importer: "Assets:MoneyFound:Yuebao".extract() raised an unexpected error: Could not determine delimiter
ERROR:root:Traceback: Traceback (most recent call last):
  File "/Users/Wong/.pyenv/versions/3.7.3/lib/python3.7/site-packages/beancount/ingest/extract.py", line 191, in extract
    allow_none_for_tags_and_links=allow_none_for_tags_and_links)
  File "/Users/Wong/.pyenv/versions/3.7.3/lib/python3.7/site-packages/beancount/ingest/extract.py", line 69, in extract_from_file
    new_entries = importer.extract(file, **kwargs)
  File "./Importers/alipay.py", line 249, in extract
    iconfig, has_header = normalize_config(self.config, file.head(-1))
  File "./Importers/alipay.py", line 435, in normalize_config
    has_header = csv.Sniffer().has_header(head)
  File "/Users/Wong/.pyenv/versions/3.7.3/lib/python3.7/csv.py", line 394, in has_header
    rdr = reader(StringIO(sample), self.sniff(sample))
  File "/Users/Wong/.pyenv/versions/3.7.3/lib/python3.7/csv.py", line 188, in sniff
    raise Error("Could not determine delimiter")
_csv.Error: Could not determine delimiter
```

**Comment by lidongchao** [comment]
CSV确定第一行是表头信息吗？而且用逗号分隔符格式存储的？
