### ISSUE TITLE
NameError: name 'regexp' is not defined

### ISSUE THREAD

**Issue by xiang578** [lidongchao/BeancountSample#3]
```
Traceback (most recent call last):
  File "/anaconda3/bin/bean-extract", line 4, in <module>
    from beancount.ingest.extract import main; main()
  File "/anaconda3/lib/python3.6/site-packages/beancount/ingest/extract.py", line 257, in main
    return scripts_utils.trampoline_to_ingest(sys.modules[__name__])
  File "/anaconda3/lib/python3.6/site-packages/beancount/ingest/scripts_utils.py", line 174, in trampoline_to_ingest
    return run_import_script_and_ingest(parser)
  File "/anaconda3/lib/python3.6/site-packages/beancount/ingest/scripts_utils.py", line 212, in run_import_script_and_ingest
    mod = runpy.run_path(args.config)
  File "/anaconda3/lib/python3.6/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/anaconda3/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "my.config", line 4, in <module>
    from alipay import Debit_or_credit, Col, Importer
  File "./Importers/alipay.py", line 134, in <module>
    class Importer(regexp.RegexpImporterMixin, importer.ImporterProtocol):
NameError: name 'regexp' is not defined
```

git clone 之后运行脚本出现这个错误，不知道是不是和 beancount 的安装方式有关？我是用 pip 安装的

**Comment by lidongchao** [comment]
不好意思这个版本是基于2.7开发的，具体参考前一个问题，最近有升级的计划但是因为搬家所以搁置了，等弄完了这边的事就更新一下。

**Comment by xiang578** [comment]
@lidongchao 期待中
